# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    app.param_converter:
        class: AppBundle\Request\AppParamConverter
        arguments: [@doctrine_mongodb]
        tags:
            - { name: request.param_converter }
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }
    compte.manager:
        class: AppBundle\Manager\CompteManager
        arguments: [@doctrine_mongodb.odm.default_document_manager]

    etablissement.manager:
        class: AppBundle\Manager\EtablissementManager
        arguments: [@doctrine_mongodb.odm.default_document_manager,@tool.osm]

    etablissement.importer:
        class: AppBundle\Import\EtablissementCsvImporter
        arguments: [@doctrine_mongodb.odm.default_document_manager, @societe.manager, @etablissement.manager]

    paiements.importer:
        class: AppBundle\Import\PaiementsCsvImporter
        arguments: [@doctrine_mongodb.odm.default_document_manager, @paiements.manager, @facture.manager]
        
    contrat.manager:
        class: AppBundle\Manager\ContratManager
        arguments: [@doctrine_mongodb.odm.default_document_manager]

    passage.manager:
        class: AppBundle\Manager\PassageManager
        arguments: [@doctrine_mongodb.odm.default_document_manager, @contrat.manager]
        
    rendezvous.manager:
        class: AppBundle\Manager\RendezVousManager
        arguments: [@doctrine_mongodb.odm.default_document_manager]

    passage.importer:
        class: AppBundle\Import\PassageCsvImporter
        arguments: [@doctrine_mongodb.odm.default_document_manager, @passage.manager, @etablissement.manager, @compte.manager, @contrat.manager]

    paiements.manager:
        class: AppBundle\Manager\PaiementsManager
        arguments: [@doctrine_mongodb.odm.default_document_manager, @facture.manager]
        
    societe.importer:
        class: AppBundle\Import\SocieteCsvImporter
        arguments: [@doctrine_mongodb.odm.default_document_manager, @societe.manager]

    societe.manager:
        class: AppBundle\Manager\SocieteManager
        arguments: [@doctrine_mongodb.odm.default_document_manager]

    contrat.importer:
        class: AppBundle\Import\ContratCsvImporter
        arguments: [@doctrine_mongodb.odm.default_document_manager, @contrat.manager, @passage.manager, @etablissement.manager, @societe.manager, @compte.manager]

    contrat.manager:
        class: AppBundle\Manager\ContratManager
        arguments: [@doctrine_mongodb.odm.default_document_manager]

    mouvement.manager:
        class: AppBundle\Manager\MouvementManager
        arguments: [[@contrat.manager]]

    facture.manager:
        class: AppBundle\Manager\FactureManager
        arguments: [@doctrine_mongodb.odm.default_document_manager, @mouvement.manager, "%facture%"]

    facture.importer:
        class: AppBundle\Import\FactureCsvImporter
        arguments: [@doctrine_mongodb.odm.default_document_manager, @facture.manager, @societe.manager, @contrat.manager]

    tool.osm:
        class: AppBundle\Tool\OSMAdresses
        arguments: [%osm.url_search%,%osm.return_format%]

    compte.importer:
        class: AppBundle\Import\CompteCsvImporter
        arguments: [@doctrine_mongodb.odm.default_document_manager]

    configurationPrestation.importer:
        class: AppBundle\Import\ConfigurationPrestationCsvImporter
        arguments: [@doctrine_mongodb.odm.default_document_manager]

    configurationProduit.importer:
        class: AppBundle\Import\ConfigurationProduitCsvImporter
        arguments: [@doctrine_mongodb.odm.default_document_manager]

    contratPrestation.importer:
        class: AppBundle\Import\ContratPrestationCsvImporter
        arguments: [@doctrine_mongodb.odm.default_document_manager, @contrat.manager]

    contact.importer:
        class: AppBundle\Import\ContactCsvImporter
        arguments: [@doctrine_mongodb.odm.default_document_manager]
